Location: 'westeurope'
ManagementGroupPrefix: 'alz'
TopLevelManagementGroupDisplayName: 'Azure Landing Zones'
DeployAlzDefaultPolicies: 'true'
LoggingResourceGroupName: 'alz-hub-we-logging-rg'
NetworkingResourceGroupName: 'alz-hub-we-networking-rg'
LogAnalyticsWorkspaceName: 'alz-hub-we-logging-ws'
AutomationAccountName: 'alz-hub-we-automation-aa'
DeallocateFirewall: 'true'
HubNetworkName: 'alz-hub-WE-vnet'