# This is a basic workflow to help you get started with Actions

name: env-var-test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup_variables:
    name: 'Configure environment variables'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set env variables
        shell: pwsh
        run: |
          Install-Module powershell-Yaml -Force
          if (Get-Item -Path ${{ env.ConfigYamlFile }}) {
            Write-Output "Config file found. Enumerating and storing in variable"
            $config = Get-Content '${{ env.ConfigYamlFile }}' | ConvertFrom-Yaml
          }
          $config.GetEnumerator() | Foreach-Object {
            Write-Output "Setting environment variable $($_.Key)"
            echo "$($_.Key)=$($_.Value)" >> $GITHUB_ENV
          }
      - name: Write env variables
        shell: pwsh
        run: Write-Output ${{ github.env }}